'use strict'; // code generated by pbf v3.2.1

// Tensor ========================================

var Tensor = self.Tensor = {};

Tensor.read = function (pbf, end) {
    return pbf.readFields(Tensor._readField, {tag_name: "", public_dtype: ""}, end);
};
Tensor._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.tag_name = pbf.readString();
    else if (tag === 3) obj.public_dtype = pbf.readString();
};
Tensor.write = function (obj, pbf) {
    if (obj.tag_name) pbf.writeStringField(1, obj.tag_name);
    if (obj.public_dtype) pbf.writeStringField(3, obj.public_dtype);
};
